print("Hello World!")
pi = (22/7)
radius=float(input("What is the radius?"))
circumference = str(pi*radius*2)
area = str(pi*radius*radius)
print("Circumference of circle is:"+ circumference)
print("Area of circle is:"+area)
x = str(float(area)*2)
print("Area of 2 circles is:"+x)